// Codigo que roda dentro do HTML exportado, junto com o slide do Genially.
//
// Este arquivo NAO e carregado pela ferramenta: ele e uma fonte de texto que o
// gerador embute no trecho final. Por isso e escrito em ES5 puro (sem let,
// sem arrow, sem template string): o HTML pode acabar num navegador antigo de
// laboratorio de informatica, e um erro de sintaxe ali significa aula sem audio.
//
// Regra importante para quem for editar: caracteres acentuados so podem
// aparecer dentro de literais de string ou de comentarios. O gerador passa
// esta fonte inteira por um escape para \uXXXX, o que e seguro nesses dois
// contextos e em nenhum outro.

export var FONTE_RUNTIME = [
  '(function () {',
  '  "use strict";',
  '',
  '  var CFG = __SYNCLAB_CONFIG__;',
  '  var doc = document;',
  '  var raiz = doc.getElementById(CFG.id);',
  '  if (!raiz) { return; }',
  '',
  '  var caixa = raiz.querySelector(\'[data-synclab="caixa"]\');',
  '  var audio = raiz.querySelector(\'[data-synclab="audio"]\');',
  '  var cues = CFG.cues || [];',
  '  if (!caixa || !audio) { return; }',
  '',
  '  var estado = {',
  '    script: true,',
  '    legendas: cues.length,',
  '    endereco: "",',
  '    carregamento: "aguardando",',
  '    duracao: 0,',
  '    erro: "",',
  '    tocando: false,',
  '    bloqueado: false,',
  '    mudo: false,',
  '    tentativas: 0,',
  '    bloco: 0,',
  '    contexto: "",',
  '    paiEscutado: false,',
  '    encerrado: false',
  '  };',
  '',
  '  // -------------------------------------------------------------------',
  '  // Contexto: pagina principal ou dentro de um iframe.',
  '  // E este campo que revela quando o Genially embrulha o conteudo, o que',
  '  // muda completamente o comportamento do autoplay.',
  '  // -------------------------------------------------------------------',
  '  function descobrirContexto() {',
  '    var dentro;',
  '    try { dentro = window.self !== window.top; }',
  '    catch (e) { dentro = true; }',
  '',
  '    var niveis = 0;',
  '    try {',
  '      var w = window;',
  '      while (w !== w.parent && niveis < 20) { w = w.parent; niveis++; }',
  '    } catch (e2) { niveis = -1; }',
  '',
  '    var paiAcessivel = false;',
  '    try {',
  '      paiAcessivel = !!(window.parent && window.parent !== window && window.parent.document);',
  '    } catch (e3) { paiAcessivel = false; }',
  '',
  '    return (dentro ? "dentro de um iframe" : "pagina principal") +',
  '      " | niveis acima: " + (niveis < 0 ? "inacessivel" : niveis) +',
  '      " | pagina pai " + (dentro ? (paiAcessivel ? "acessivel (mesma origem)" : "bloqueada (outra origem)") : "nao se aplica");',
  '  }',
  '  estado.contexto = descobrirContexto();',
  '',
  '  // -------------------------------------------------------------------',
  '  // Legenda',
  '  // -------------------------------------------------------------------',
  '  var indiceAtual = -2;',
  '',
  '  function indicePara(t) {',
  '    var lo = 0;',
  '    var hi = cues.length - 1;',
  '    while (lo <= hi) {',
  '      var meio = (lo + hi) >> 1;',
  '      if (t < cues[meio][0]) { hi = meio - 1; }',
  '      else if (t > cues[meio][1]) { lo = meio + 1; }',
  '      else { return meio; }',
  '    }',
  '    return -1;',
  '  }',
  '',
  '  function mostrar(i) {',
  '    if (i === indiceAtual) { return; }',
  '    indiceAtual = i;',
  '    estado.bloco = i + 1;',
  '    if (i < 0) {',
  '      caixa.setAttribute("data-visivel", "0");',
  '      return;',
  '    }',
  '    caixa.textContent = cues[i][2];',
  '    caixa.setAttribute("data-visivel", "1");',
  '  }',
  '',
  '  var quadroPedido = false;',
  '  function quadro() {',
  '    quadroPedido = false;',
  '    if (!estado.encerrado) {',
  '      mostrar(indicePara(audio.currentTime));',
  '      estado.tocando = !audio.paused && !audio.ended;',
  '      agendarQuadro();',
  '    }',
  '  }',
  '  function agendarQuadro() {',
  '    if (quadroPedido || estado.encerrado) { return; }',
  '    quadroPedido = true;',
  '    if (window.requestAnimationFrame) { window.requestAnimationFrame(quadro); }',
  '    else { window.setTimeout(quadro, 50); }',
  '  }',
  '',
  '  // -------------------------------------------------------------------',
  '  // Autoplay',
  '  //',
  '  // A tentativa nao acontece uma vez so: ela se repete a cada 400 ms ate o',
  '  // audio estar tocando com som. Se o navegador recusar o som, o audio toca',
  '  // mudo -- o que nenhum navegador bloqueia -- para nao perder a sincronia',
  '  // com o slide, e a tentativa de devolver o som continua em segundo plano.',
  '  // -------------------------------------------------------------------',
  '  var intervalo = null;',
  '  var testandoDesmute = false;',
  '',
  '  function nomeDoErro(erro) {',
  '    if (!erro) { return "erro desconhecido"; }',
  '    return (erro.name || "Erro") + ": " + (erro.message || "");',
  '  }',
  '',
  '  function tocar() {',
  '    var p;',
  '    try { p = audio.play(); }',
  '    catch (e) { estado.erro = nomeDoErro(e); return null; }',
  '    return p && typeof p.then === "function" ? p : null;',
  '  }',
  '',
  '  function tentativa() {',
  '    if (estado.encerrado) { return; }',
  '',
  '    if (audio.ended) { finalizar(); return; }',
  '',
  '    if (audio.paused) {',
  '      estado.tentativas++;',
  '      var promessa = tocar();',
  '      if (promessa) {',
  '        promessa.then(function () {',
  '          estado.bloqueado = false;',
  '          // Deu certo: o erro anterior virou historia e nao deve continuar',
  '          // no painel, senao parece falha em algo que ja se resolveu.',
  '          estado.erro = "";',
  '        })["catch"](function (erro) {',
  '          estado.erro = nomeDoErro(erro);',
  '          estado.bloqueado = true;',
  '          // Plano B: mudo sempre e permitido. Melhor tocar sem som e manter',
  '          // a legenda no tempo certo do que nao tocar nada.',
  '          if (!audio.muted) {',
  '            audio.muted = true;',
  '            estado.mudo = true;',
  '            var segunda = tocar();',
  '            if (segunda) {',
  '              segunda["catch"](function (e2) { estado.erro = nomeDoErro(e2); });',
  '            }',
  '          }',
  '        });',
  '      }',
  '      return;',
  '    }',
  '',
  '    if (audio.muted) {',
  '      // Esta tocando mudo. Tenta devolver o som sem reiniciar nada: a posicao',
  '      // atual e preservada, entao a sincronia nao se perde no processo.',
  '      if (testandoDesmute) { return; }',
  '      testandoDesmute = true;',
  '      audio.muted = false;',
  '      window.setTimeout(function () {',
  '        testandoDesmute = false;',
  '        if (audio.muted || audio.paused) {',
  '          // O navegador recusou: volta para o mudo e segue tentando.',
  '          audio.muted = true;',
  '          estado.mudo = true;',
  '          estado.bloqueado = true;',
  '          if (audio.paused && !audio.ended) { tocar(); }',
  '        } else {',
  '          estado.mudo = false;',
  '          estado.bloqueado = false;',
  '        }',
  '      }, 80);',
  '      return;',
  '    }',
  '',
  '    // Tocando e com som: e o estado desejado.',
  '    estado.mudo = false;',
  '    estado.bloqueado = false;',
  '  }',
  '',
  '  function finalizar() {',
  '    if (estado.encerrado) { return; }',
  '    estado.encerrado = true;',
  '    estado.tocando = false;',
  '    if (intervalo) { window.clearInterval(intervalo); intervalo = null; }',
  '    caixa.setAttribute("data-visivel", "0");',
  '    atualizarPainel();',
  '  }',
  '',
  '  // -------------------------------------------------------------------',
  '  // Interacao do usuario: qualquer gesto libera o som.',
  '  // -------------------------------------------------------------------',
  '  var EVENTOS = ["pointerdown", "mousedown", "touchstart", "touchend",',
  '                 "keydown", "click", "scroll", "wheel"];',
  '',
  '  function aoInteragir() {',
  '    if (estado.encerrado) { return; }',
  '    if (audio.muted) { audio.muted = false; estado.mudo = false; }',
  '    if (audio.paused) { tocar(); }',
  '    tentativa();',
  '  }',
  '',
  '  function escutar(alvo) {',
  '    if (!alvo || !alvo.addEventListener) { return false; }',
  '    var opcoes;',
  '    try {',
  '      // Detecta suporte a options object; navegadores antigos leem booleano.',
  '      var testado = false;',
  '      var teste = Object.defineProperty({}, "passive", {',
  '        get: function () { testado = true; return true; }',
  '      });',
  '      alvo.addEventListener("synclabteste", null, teste);',
  '      alvo.removeEventListener("synclabteste", null, teste);',
  '      opcoes = testado ? { passive: true, capture: true } : true;',
  '    } catch (e) { opcoes = true; }',
  '',
  '    for (var i = 0; i < EVENTOS.length; i++) {',
  '      try { alvo.addEventListener(EVENTOS[i], aoInteragir, opcoes); }',
  '      catch (e2) { /* evento nao suportado neste navegador */ }',
  '    }',
  '    return true;',
  '  }',
  '',
  '  escutar(doc);',
  '  escutar(window);',
  '',
  '  // A pagina pai so e alcancavel quando esta na mesma origem. Dentro do',
  '  // Genially isso costuma falhar, e falhar aqui e esperado -- por isso a',
  '  // tentativa fica em try/catch e o resultado vai para o diagnostico.',
  '  try {',
  '    if (window.parent && window.parent !== window && window.parent.document) {',
  '      estado.paiEscutado = escutar(window.parent.document);',
  '    }',
  '  } catch (e) { estado.paiEscutado = false; }',
  '  try {',
  '    if (window.top && window.top !== window && window.top !== window.parent && window.top.document) {',
  '      escutar(window.top.document);',
  '    }',
  '  } catch (e) { /* topo em outra origem */ }',
  '',
  '  try {',
  '    doc.addEventListener("visibilitychange", function () {',
  '      if (!doc.hidden) { tentativa(); }',
  '    });',
  '  } catch (e) { /* sem suporte */ }',
  '',
  '  // -------------------------------------------------------------------',
  '  // Diagnostico',
  '  // -------------------------------------------------------------------',
  '  function descreverMidia() {',
  '    var err = audio.error;',
  '    if (!err) { return ""; }',
  '    switch (err.code) {',
  '      case 1: return "carregamento cancelado (MEDIA_ERR_ABORTED)";',
  '      case 2: return "falha de rede ao baixar o audio (MEDIA_ERR_NETWORK) - confira a URL e o CORS do bucket";',
  '      case 3: return "falha ao decodificar (MEDIA_ERR_DECODE) - o arquivo pode estar corrompido";',
  '      case 4: return "endereco inacessivel ou formato nao suportado (MEDIA_ERR_SRC_NOT_SUPPORTED) - abra a URL do audio no navegador para conferir";',
  '      default: return "codigo " + err.code;',
  '    }',
  '  }',
  '',
  '  var ESTADOS_REDE = ["vazio", "ocioso", "carregando", "sem fonte"];',
  '  var ESTADOS_PRONTIDAO = ["nada carregado", "metadados", "dados atuais", "pouco a frente", "carregado o bastante"];',
  '',
  '  var painel = null;',
  '  function criarPainel() {',
  '    if (!CFG.diagnostico) { return; }',
  '    painel = doc.createElement("div");',
  '    painel.className = CFG.prefixo + "-diag";',
  '    painel.setAttribute("data-synclab", "diagnostico");',
  '    raiz.appendChild(painel);',
  '  }',
  '',
  '  function marca(ok, textoOk, textoRuim) {',
  '    var classe = ok ? CFG.prefixo + "-ok" : CFG.prefixo + "-erro";',
  '    return \'<span class="\' + classe + \'">\' + (ok ? textoOk : textoRuim) + "</span>";',
  '  }',
  '',
  '  function escapar(texto) {',
  '    return String(texto === null || texto === undefined ? "" : texto)',
  '      .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");',
  '  }',
  '',
  '  var ultimoPainel = 0;',
  '  function atualizarPainel() {',
  '    if (!painel) { return; }',
  '    var agora = Date.now();',
  '    if (agora - ultimoPainel < 200 && !estado.encerrado) { return; }',
  '    ultimoPainel = agora;',
  '',
  '    var midia = descreverMidia();',
  '    var linhas = [',
  '      "<b>SyncLab - diagnostico</b>",',
  '      "script rodou: " + marca(true, "sim", "nao"),',
  '      "legendas carregadas: " + marca(estado.legendas > 0, String(estado.legendas), "0 (nenhuma legenda embutida)"),',
  '      "bloco atual: " + (estado.bloco > 0 ? estado.bloco + " de " + estado.legendas : "nenhum"),',
  '      "endereco do audio: " + escapar(estado.endereco),',
  '      "estado da rede: " + escapar(ESTADOS_REDE[audio.networkState] || audio.networkState),',
  '      "carregamento: " + escapar(ESTADOS_PRONTIDAO[audio.readyState] || audio.readyState),',
  '      "duracao: " + (isFinite(audio.duration) && audio.duration > 0 ? audio.duration.toFixed(2) + "s" : "ainda desconhecida"),',
  '      "posicao: " + (isFinite(audio.currentTime) ? audio.currentTime.toFixed(2) + "s" : "-"),',
  '      "tocando: " + marca(!audio.paused && !audio.ended, "sim", audio.ended ? "terminou" : "nao"),',
  '      "som: " + (audio.muted ? \'<span class="\' + CFG.prefixo + \'-alerta">mudo (fallback ativo)</span>\' : marca(true, "ligado", "-")),',
  '      "bloqueado pelo navegador: " + (estado.bloqueado ? \'<span class="\' + CFG.prefixo + \'-erro">sim</span>\' : \'<span class="\' + CFG.prefixo + \'-ok">nao</span>\'),',
  '      "tentativas de play: " + estado.tentativas,',
  '      "contexto: " + escapar(estado.contexto),',
  '      "escuta na pagina pai: " + (estado.paiEscutado ? "sim" : "nao (outra origem ou sem pai)"),',
  '      "erro: " + (midia || estado.erro',
  '        ? \'<span class="\' + CFG.prefixo + \'-erro">\' + escapar(midia || estado.erro) + "</span>"',
  '        : \'<span class="\' + CFG.prefixo + \'-ok">nenhum</span>\')',
  '    ];',
  '    painel.innerHTML = linhas.join("<br>");',
  '  }',
  '',
  '  // -------------------------------------------------------------------',
  '  // Partida',
  '  // -------------------------------------------------------------------',
  '  function ligarEventosDoAudio() {',
  '    var eventos = ["loadstart", "loadedmetadata", "loadeddata", "canplay",',
  '                   "canplaythrough", "playing", "play", "pause", "waiting",',
  '                   "stalled", "suspend", "error", "ended", "timeupdate"];',
  '    for (var i = 0; i < eventos.length; i++) {',
  '      (function (nome) {',
  '        audio.addEventListener(nome, function () {',
  '          if (nome === "ended") { finalizar(); }',
  '          if (nome === "error") { estado.erro = descreverMidia(); }',
  '          if (nome === "loadedmetadata" && isFinite(audio.duration)) { estado.duracao = audio.duration; }',
  '          if (nome === "playing") { estado.bloqueado = false; estado.erro = ""; }',
  '          atualizarPainel();',
  '        });',
  '      })(eventos[i]);',
  '    }',
  '  }',
  '',
  '  criarPainel();',
  '  ligarEventosDoAudio();',
  '',
  '  audio.loop = false;',
  '  audio.preload = "auto";',
  '  audio.setAttribute("playsinline", "");',
  '  audio.setAttribute("webkit-playsinline", "");',
  '  if (CFG.volume !== null && CFG.volume !== undefined) { audio.volume = CFG.volume; }',
  '',
  '  estado.endereco = CFG.audioEmbutido',
  '    ? "audio embutido no proprio HTML (data URI, " + CFG.tamanhoAudio + " bytes)"',
  '    : CFG.audio;',
  '  audio.src = CFG.audio;',
  '',
  '  try { audio.load(); } catch (e) { /* alguns navegadores dispensam */ }',
  '',
  '  mostrar(-1);',
  '  agendarQuadro();',
  '  tentativa();',
  '  intervalo = window.setInterval(tentativa, CFG.intervaloTentativa || 400);',
  '  window.setInterval(atualizarPainel, 500);',
  '  atualizarPainel();',
  '})();'
].join('\n');
